name: Build UptimeWidget Installer

on:
  workflow_run:
    workflows:
      - Build UptimeWidget
    types:
      - completed

permissions:
  actions: read
  contents: read


jobs:
  build_installer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: UptimeWidget-build-artifact
          path: UptimeWidget-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show artifact files
        shell: pwsh
        run: |
          Get-ChildItem UptimeWidget-build -Recurse

      - name: dotnet version
        run: dotnet --version

      - name: Install WiX ClI
        run: dotnet tool install --global WiX
        
      - name: WiX version
        run: wix --version


