name: Build UptimeWidget Installer

on:
  workflow_run:
    workflows:
      - Build UptimeWidget
    types:
      - completed

permissions:
  actions: read
  contents: read


jobs:
  build_installer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug workflow info
        shell: pwsh
        run: |
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: UptimeWidget-build-artifact
          path: UptimeWidget-build
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show artifact files
        shell: pwsh
        run: |
          Get-ChildItem UptimeWidget-build -Recurse

      - name: dotnet version
        run: dotnet --version

      - name: Install WiX ClI
        run: dotnet tool install --global WiX
        
      - name: WiX version
        run: wix --version


