name: Build UptimeWidget

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONFIGURATION: Release
  PLATFORM: x64
  UptimeWidget_SOLUTION: UptimeWidget/UptimeWidget.slnx
  
jobs:
  build_UptimeWidget:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: dotnet version
        run: dotnet --version

      - name: Build UptimeWidget
        run: |
          dotnet build "$env:UptimeWidget_SOLUTION" --configuration "$env:CONFIGURATION"

      - name: List all files recursively
        if: github.ref != 'refs/heads/main'
        shell: pwsh
        run: |
          Write-Host "Current directory:"
          Get-Location

          Write-Host "Files and folders:"
          Get-ChildItem -Path . -Recurse -Force

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UptimeWidget-build-artifact
          path: |
            UptimeWidget/UptimeWidget/bin/${{ env.PLATFORM }}/${{ env.CONFIGURATION }}/net10.0-windows/
            !UptimeWidget/UptimeWidget/bin/${{ env.PLATFORM }}/${{ env.CONFIGURATION }}/net10.0-windows/**/*.pdb

      # - name: Install WiX ClI
      #   run: dotnet tool install --global WiX
        
      # - name: WiX version
      #   run: wix --version

      # - name: Build UptimeWidget Installer
      #   run: |
      #     cd UptimeWidgetInstaller
      #     wix build UptimeWidgetInstaller.wixproj -o ../UptimeWidgetInstaller/bin/Release/UptimeWidgetInstaller.msi